-- PART 1: Run this FIRST to create the tables.

-- Admin Users Table
create table if not exists admin_users (
  id uuid references auth.users not null primary key,
  email text not null,
  role text not null check (role in ('super_admin', 'admin_manager', 'content_manager', 'support_staff', 'analytics_viewer')),
  status text not null default 'active' check (status in ('active', 'suspended')),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS
alter table admin_users enable row level security;

create policy "Super Admins can manage all"
on admin_users
for all
to authenticated
using (
  exists (
    select 1 from admin_users au
    where au.id = auth.uid() and au.role = 'super_admin'
  )
);

create policy "Users can view own profile"
on admin_users
for select
to authenticated
using (
  auth.uid() = id
);

-- Activity Logs Table
create table if not exists activity_logs (
  id bigint generated by default as identity primary key,
  user_email text not null,
  action text not null,
  details jsonb,
  timestamp timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS
alter table activity_logs enable row level security;

create policy "Admins can insert logs"
on activity_logs
for insert
to authenticated
with check (true);

create policy "Admins can view logs"
on activity_logs
for select
to authenticated
using (
  exists (
    select 1 from admin_users au
    where au.id = auth.uid() and au.role in ('super_admin', 'admin_manager')
  )
);
