-- Create a table for partner inquiries
create table partner_inquiries (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  email text not null,
  phone text,
  message text not null
);

-- Enable RLS
alter table partner_inquiries enable row level security;

-- Allow anyone (public/anon) to insert inquiries
create policy "Enable insert for everyone"
on partner_inquiries for insert
with check ( true );

-- Only allow authenticated users (admin) to view inquiries (optional security measure)
-- For now, if we don't have auth setup fully for admin, we might want to allow public read or just keep it write-only for public.
-- Let's keep it write-only for public to prevent spam visibility.
