-- KIDS-CAN DEFINITIVE DATABASE ARCHITECTURE
-- Run this in the Supabase SQL Editor to ensure all advanced collections are ready.

-- 1. TEAMS COLLECTION
create table if not exists teams (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  team_name text not null,
  captain_name text not null,
  contact_number text,
  email text,
  members_count int default 2,
  payment_status text default 'Pending', -- Pending / Paid
  event_selected text,
  notes text
);

-- 2. DONATIONS COLLECTION
create table if not exists donors (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  donor_name text not null,
  email text,
  amount decimal(10,2) not null,
  method text default 'GivePulse', -- GivePulse, EFT, Cash, Stripe
  hero_id bigint references heroes(id), -- Linked Child
  status text default 'Completed',
  transaction_id text -- For payment gateway tracking
);

-- 3. HEROES COLLECTION (ADMIN CONTROLLED)
create table if not exists heroes (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  age text,
  diagnosis text,
  story text,
  image text,
  fundraising_goal decimal(10,2) default 0.00,
  amount_raised decimal(10,2) default 0.00,
  status text default 'Active' -- Active / Funded / Completed
);

-- 4. NOTIFICATIONS COLLECTION (REAL-TIME)
create table if not exists admin_notifications (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  message text,
  type text, -- registration / donation / system
  is_read boolean default false
);

-- 5. ENABLE RLS (Row Level Security)
alter table teams enable row level security;
alter table donors enable row level security;
alter table heroes enable row level security;
alter table admin_notifications enable row level security;

-- PUBLIC POLICIES
create policy "Public can register teams" on teams for insert with check (true);
create policy "Public can submit donations" on donors for insert with check (true);
create policy "Public can view heroes" on heroes for select using (true);

-- ADMIN POLICIES (Authenticated users)
create policy "Admins can manage teams" on teams for all to authenticated using (true);
create policy "Admins can manage donors" on donors for all to authenticated using (true);
create policy "Admins can manage heroes" on heroes for all to authenticated using (true);
create policy "Admins can manage notifications" on admin_notifications for all to authenticated using (true);

-- 6. REAL-TIME REPLICATION
-- Run this part if you have permissions, or enable via Supabase UI:
-- alter publication supabase_realtime add table admin_notifications;
-- alter publication supabase_realtime add table teams;
-- alter publication supabase_realtime add table donors;
