-- Admin Dashboard V2: New Tables for Teams, Donors and Enhanced Heroes

-- 1. TEAMS TABLE
create table if not exists teams (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  team_name text not null,
  captain_name text not null,
  contact_number text,
  email text,
  members_count int default 2,
  payment_status text default 'Pending', -- Pending, Paid
  event_id bigint references events(id) -- Optional link to specific event
);

-- Enable RLS
alter table teams enable row level security;

-- Policies for Teams
create policy "Public can register teams" on teams for insert with check (true);
create policy "Admins can manage teams" on teams for all to authenticated
using (
  exists (
    select 1 from admin_users au
    where au.email = auth.email()
    and au.role in ('super_admin', 'admin_manager', 'volunteer_manager')
  )
);

-- 2. DONORS TABLE
create table if not exists donors (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  donor_name text not null,
  email text,
  amount decimal(10,2) not null,
  method text default 'GivePulse', -- GivePulse, EFT, Cash, Stripe
  hero_id bigint references heroes(id), -- Optional link to a specific child
  status text default 'Completed'
);

-- Enable RLS
alter table donors enable row level security;

-- Policies for Donors
create policy "Admins can view/manage donors" on donors for all to authenticated
using (
  exists (
    select 1 from admin_users au
    where au.email = auth.email()
    and au.role in ('super_admin', 'admin_manager', 'finance_manager')
  )
);

-- 3. UPGRADE HEROES TABLE (Add Status and Raised Amount)
alter table heroes add column if not exists status text default 'Active'; -- Active, Completed, Funded
alter table heroes add column if not exists amount_raised decimal(10,2) default 0.00;
alter table heroes add column if not exists fundraising_goal decimal(10,2) default 0.00;
