-- COMPREHENSIVE FIX FOR SCHEMA AND ACCESS ERRORS
-- Run this in the Supabase SQL Editor.

-- 1. Ensure Columns exist in Events (Prevent "already exists" error)
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='events' AND column_name='image_url') THEN
        ALTER TABLE events ADD COLUMN image_url text;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='events' AND column_name='video_url') THEN
        ALTER TABLE events ADD COLUMN video_url text;
    END IF;
END $$;

-- 2. Ensure Applications table exists
CREATE TABLE IF NOT EXISTS applications (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  guardian_name text not null,
  guardian_email text not null,
  guardian_phone text not null,
  relationship text not null,
  child_name text not null,
  child_age int not null,
  diagnosis text not null,
  assistance_type text not null,
  details text,
  status text default 'Pending'
);

-- 3. Ensure Contacts table exists
CREATE TABLE IF NOT EXISTS contacts (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  email text not null,
  subject text,
  message text not null,
  status text default 'New'
);

-- 4. Ensure site_content has the 'content' column (Matching admin.js)
DO $$
BEGIN
    -- If 'value' column exists but 'content' does not, rename it
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='site_content' AND column_name='value') 
    AND NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='site_content' AND column_name='content') THEN
        ALTER TABLE site_content RENAME COLUMN value TO content;
    END IF;
    
    -- Ensure 'type' column exists
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='site_content' AND column_name='type') THEN
        ALTER TABLE site_content ADD COLUMN type text DEFAULT 'text';
    END IF;
END $$;

-- 5. Permissions Check
ALTER TABLE applications ENABLE ROW LEVEL SECURITY;
ALTER TABLE contacts ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public can submit applications" ON applications;
CREATE POLICY "Public can submit applications" ON applications FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Admins can manage applications" ON applications;
CREATE POLICY "Admins can manage applications" ON applications FOR ALL TO authenticated USING (true);

DROP POLICY IF EXISTS "Public can submit contact messages" ON contacts;
CREATE POLICY "Public can submit contact messages" ON contacts FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Admins can manage contacts" ON contacts;
CREATE POLICY "Admins can manage contacts" ON contacts FOR ALL TO authenticated USING (true);

-- 6. Ensure Admin Users table is correctly structured and you are a Super Admin
DO $$
BEGIN
    -- Check if table exists
    IF EXISTS (SELECT 1 FROM pg_tables WHERE schemaname = 'public' AND tablename = 'admin_users') THEN
        -- Check if 'id' column is missing or if it's the old 'email-only' version
        IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='admin_users' AND column_name='id') THEN
            -- Old version detected. We need to recreate it to support UUID links to auth.users.
            -- 1. Rename old table to backup just in case
            ALTER TABLE admin_users RENAME TO admin_users_old;
            
            -- 2. Create correct version
            CREATE TABLE admin_users (
                id uuid references auth.users not null primary key,
                email text not null,
                role text not null,
                status text default 'active',
                created_at timestamp with time zone default timezone('utc'::text, now()) not null
            );
            
            -- 3. Restore data if possible (mapping by email)
            INSERT INTO admin_users (id, email, role, status)
            SELECT u.id, o.email, o.role, 'active'
            FROM admin_users_old o
            JOIN auth.users u ON o.email = u.email;
            
            -- 4. Enable RLS and re-create policies
            ALTER TABLE admin_users ENABLE ROW LEVEL SECURITY;
            
            DROP POLICY IF EXISTS "Users can read own role" ON admin_users;
            CREATE POLICY "Users can read own role" ON admin_users FOR SELECT USING ( auth.uid() = id );
            
            DROP POLICY IF EXISTS "Super Admins can manage all" ON admin_users;
            CREATE POLICY "Super Admins can manage all" ON admin_users FOR ALL USING (
                EXISTS (SELECT 1 FROM admin_users au WHERE au.id = auth.uid() AND au.role IN ('super_admin', 'admin_manager'))
            );
            
            -- 5. Drop old table
            DROP TABLE admin_users_old;
        END IF;
    ELSE
        -- Table doesn't exist at all, create it fresh
        CREATE TABLE admin_users (
            id uuid references auth.users not null primary key,
            email text not null,
            role text not null,
            status text default 'active',
            created_at timestamp with time zone default timezone('utc'::text, now()) not null
        );
        ALTER TABLE admin_users ENABLE ROW LEVEL SECURITY;
        CREATE POLICY "Users can read own role" ON admin_users FOR SELECT USING ( auth.uid() = id );
        CREATE POLICY "Super Admins can manage all" ON admin_users FOR ALL USING (
            EXISTS (SELECT 1 FROM admin_users au WHERE au.id = auth.uid() AND au.role IN ('super_admin', 'admin_manager'))
        );
    END IF;
END $$;

-- Add yourself as Super Admin
INSERT INTO admin_users (id, email, role, status)
SELECT id, email, 'super_admin', 'active'
FROM auth.users
WHERE email ILIKE '%kidscan%'
ON CONFLICT (id) DO UPDATE
SET role = 'super_admin', status = 'active';
