-- MASTER SUPABASE FIX v3: Schema Migration + Clean Security
-- Run this in the Supabase SQL Editor.

-- ==========================================
-- 1. CLEAR THE WAY (Drop all policies first)
-- ==========================================
-- This prevents "cannot drop table because policies depend on it" errors
DO $$ 
DECLARE pol RECORD;
BEGIN 
    FOR pol IN (SELECT policyname, tablename FROM pg_policies WHERE schemaname = 'public') 
    LOOP EXECUTE format('DROP POLICY IF EXISTS %I ON %I', pol.policyname, pol.tablename); END LOOP; 
END $$;

-- ==========================================
-- 2. ROBUST TABLE MIGRATION (Fixes "id" missing errors)
-- ==========================================
DO $$
BEGIN
    -- Check for old admin_users (email-based) vs new (UUID-based)
    IF EXISTS (SELECT 1 FROM pg_tables WHERE schemaname = 'public' AND tablename = 'admin_users') THEN
        IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='admin_users' AND column_name='id') THEN
            RAISE NOTICE 'Old version of admin_users detected. Migrating...';
            ALTER TABLE admin_users RENAME TO admin_users_old;
            
            CREATE TABLE admin_users (
                id uuid references auth.users not null primary key,
                email text not null,
                role text not null,
                status text default 'active',
                created_at timestamp with time zone default timezone('utc'::text, now()) not null
            );
            
            -- Try to recover users who are already in auth.users
            INSERT INTO admin_users (id, email, role, status)
            SELECT u.id, o.email, o.role, 'active'
            FROM admin_users_old o
            JOIN auth.users u ON o.email = u.email;
            
            DROP TABLE admin_users_old;
        END IF;
    ELSE
        CREATE TABLE admin_users (
            id uuid references auth.users not null primary key,
            email text not null,
            role text not null,
            status text default 'active',
            created_at timestamp with time zone default timezone('utc'::text, now()) not null
        );
    END IF;

    -- Ensure other tables exist (using id bigint)
    CREATE TABLE IF NOT EXISTS applications (
      id bigint generated by default as identity primary key,
      created_at timestamp with time zone default timezone('utc'::text, now()) not null,
      guardian_name text, guardian_email text, guardian_phone text, child_name text, diagnosis text, status text default 'Pending'
    );

    CREATE TABLE IF NOT EXISTS contacts (
      id bigint generated by default as identity primary key,
      created_at timestamp with time zone default timezone('utc'::text, now()) not null,
      name text, email text, subject text, message text, status text default 'New'
    );

    CREATE TABLE IF NOT EXISTS site_content (
      id bigint generated by default as identity primary key,
      key text unique not null, content text, type text default 'text', updated_at timestamp with time zone default timezone('utc'::text, now()) not null
    );

    CREATE TABLE IF NOT EXISTS heroes (
      id bigint generated by default as identity primary key,
      name text not null, story text, image_url text, status text default 'Active'
    );

    CREATE TABLE IF NOT EXISTS teams (
      id bigint generated by default as identity primary key,
      team_name text not null, captain_name text, payment_status text default 'Pending'
    );
END $$;

-- ==========================================
-- 3. HELPER FUNCTION (Bypasses RLS Recursion)
-- ==========================================
CREATE OR REPLACE FUNCTION check_admin_role(required_roles text[])
RETURNS boolean AS $$
BEGIN
  RETURN EXISTS (
    SELECT 1 FROM admin_users
    WHERE id = auth.uid() AND role = ANY(required_roles)
  );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- ==========================================
-- 4. APPLY CLEAN POLICIES
-- ==========================================

-- Enable RLS
ALTER TABLE admin_users ENABLE ROW LEVEL SECURITY;
ALTER TABLE site_content ENABLE ROW LEVEL SECURITY;
ALTER TABLE heroes ENABLE ROW LEVEL SECURITY;
ALTER TABLE applications ENABLE ROW LEVEL SECURITY;
ALTER TABLE contacts ENABLE ROW LEVEL SECURITY;
ALTER TABLE teams ENABLE ROW LEVEL SECURITY;

-- Policies
CREATE POLICY "Users read own role" ON admin_users FOR SELECT USING ( auth.uid() = id );
CREATE POLICY "Super Admins manage admin_users" ON admin_users FOR ALL USING ( check_admin_role(ARRAY['super_admin', 'admin_manager']) );
CREATE POLICY "Public view content" ON site_content FOR SELECT USING (true);
CREATE POLICY "Admins manage content" ON site_content FOR ALL USING ( check_admin_role(ARRAY['super_admin', 'content_manager', 'admin_manager']) );
CREATE POLICY "Public view heroes" ON heroes FOR SELECT USING (true);
CREATE POLICY "Admins manage heroes" ON heroes FOR ALL USING ( check_admin_role(ARRAY['super_admin', 'content_manager', 'admin_manager']) );
CREATE POLICY "Public submit apps" ON applications FOR INSERT WITH CHECK (true);
CREATE POLICY "Admins manage apps" ON applications FOR ALL USING ( check_admin_role(ARRAY['super_admin', 'support_staff', 'admin_manager']) );
CREATE POLICY "Public submit contact" ON contacts FOR INSERT WITH CHECK (true);
CREATE POLICY "Admins manage contact" ON contacts FOR ALL USING ( check_admin_role(ARRAY['super_admin', 'support_staff', 'admin_manager']) );
CREATE POLICY "Public submit teams" ON teams FOR INSERT WITH CHECK (true);
CREATE POLICY "Admins manage teams" ON teams FOR ALL USING ( check_admin_role(ARRAY['super_admin', 'support_staff', 'admin_manager']) );

-- ==========================================
-- 5. FINAL SETUP (SUPER ADMIN)
-- ==========================================
INSERT INTO admin_users (id, email, role, status)
SELECT id, email, 'super_admin', 'active'
FROM auth.users
WHERE email ILIKE '%kidscan%' OR email ILIKE '%netizen%'
ON CONFLICT (id) DO UPDATE SET role = 'super_admin';
