-- MASTER SUPABASE SCHEMA FOR KIDS-CAN DASHBOARD V2
-- Run this in the Supabase SQL Editor to restore all functionality.

-- 1. Heroes Table
CREATE TABLE IF NOT EXISTS heroes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  name TEXT NOT NULL,
  age TEXT,
  diagnosis TEXT,
  story TEXT,
  image TEXT,
  amount_raised DECIMAL DEFAULT 0,
  fundraising_goal DECIMAL DEFAULT 10000,
  status TEXT DEFAULT 'Active'
);

-- 2. Teams Table
CREATE TABLE IF NOT EXISTS teams (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  team_name TEXT NOT NULL,
  captain_name TEXT,
  members_count INT DEFAULT 2,
  payment_status TEXT DEFAULT 'Pending'
);

-- 3. Donors Table (Financial Records)
CREATE TABLE IF NOT EXISTS donors (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  donor_name TEXT NOT NULL,
  email TEXT,
  amount DECIMAL NOT NULL,
  method TEXT DEFAULT 'Other',
  hero_id BIGINT REFERENCES heroes(id),
  transaction_id TEXT
);

-- 4. Events Table
CREATE TABLE IF NOT EXISTS events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  title TEXT NOT NULL,
  date DATE,
  location TEXT,
  description TEXT,
  image_url TEXT,
  video_url TEXT
);

-- 5. Admin Users (RBAC)
CREATE TABLE IF NOT EXISTS admin_users (
  id UUID PRIMARY KEY REFERENCES auth.users(id),
  email TEXT UNIQUE NOT NULL,
  role TEXT DEFAULT 'analytics_viewer',
  status TEXT DEFAULT 'active',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 6. Page Views (Analytics)
CREATE TABLE IF NOT EXISTS page_views (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  viewed_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  path TEXT NOT NULL,
  user_agent TEXT
);

-- 7. Activity Logs
CREATE TABLE IF NOT EXISTS activity_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  user_email TEXT NOT NULL,
  action TEXT NOT NULL,
  details TEXT
);

-- 8. Admin Notifications
CREATE TABLE IF NOT EXISTS admin_notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  title TEXT NOT NULL,
  message TEXT,
  type TEXT DEFAULT 'info',
  is_read BOOLEAN DEFAULT FALSE
);

-- 9. About Page Content
CREATE TABLE IF NOT EXISTS about_page (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  mission TEXT,
  mission_extended TEXT,
  gallery JSONB DEFAULT '[]'::JSONB
);

-- 10. Site Content (Visual Editor Keys)
CREATE TABLE IF NOT EXISTS site_content (
  key TEXT PRIMARY KEY,
  content TEXT,
  type TEXT DEFAULT 'text'
);

-- SEED DATA (If empty)
INSERT INTO about_page (mission, mission_extended, gallery)
SELECT 'Our mission is to bring hope, dignity, and support to children...', 'Founded on compassion...', '[]'
WHERE NOT EXISTS (SELECT 1 FROM about_page);

-- ENABLE REALTIME
ALTER PUBLICATION supabase_realtime ADD TABLE admin_notifications;
ALTER PUBLICATION supabase_realtime ADD TABLE teams;
ALTER PUBLICATION supabase_realtime ADD TABLE donors;
ALTER PUBLICATION supabase_realtime ADD TABLE heroes;
