-- Additional tables for Kids-Can Website

-- 1. APPLICATIONS COLLECTION
create table if not exists applications (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  guardian_name text not null,
  guardian_email text not null,
  guardian_phone text not null,
  relationship text not null,
  child_name text not null,
  child_age int not null,
  diagnosis text not null,
  assistance_type text not null,
  details text,
  status text default 'Pending' -- Pending / Approved / Rejected / Completed
);

-- 2. CONTACTS COLLECTION
create table if not exists contacts (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  email text not null,
  subject text,
  message text not null,
  status text default 'New' -- New / Read / Replied
);

-- 3. ENABLE RLS
alter table applications enable row level security;
alter table contacts enable row level security;

-- 4. PUBLIC POLICIES
create policy "Public can submit applications" on applications for insert with check (true);
create policy "Public can submit contact messages" on contacts for insert with check (true);
create policy "Public can view their own applications" on applications for select using (true); -- Simplified for now

-- 5. ADMIN POLICIES
create policy "Admins can manage applications" on applications for all to authenticated using (true);
create policy "Admins can manage contacts" on contacts for all to authenticated using (true);

-- 6. REAL-TIME REPLICATION
-- alter publication supabase_realtime add table applications;
-- alter publication supabase_realtime add table contacts;
