-- Create page_views table
create table if not exists page_views (
  id bigint generated by default as identity primary key,
  viewed_at timestamp with time zone default timezone('utc'::text, now()) not null,
  path text not null,
  user_agent text
);

-- Enable RLS
alter table page_views enable row level security;

-- Create policy to allow anonymous inserts (for tracking)
create policy "Allow anonymous inserts"
on page_views
for insert
to anon
with check (true);

-- Create policy to allow admins to view data
-- Assuming admin_users table exists and RLS is set up there, but for simplicity:
-- If using service_role or authenticated users with specific roles:
-- create policy "Allow admins to view"
-- on page_views
-- for select
-- to authenticated
-- using (true);
-- For now, allowing anon read might be unsafe if we want private analytics, 
-- but given the 'anon key' usage in admin.js for fetching analytics, we might need public read 
-- OR use a specific function. 
-- Let's stick to allowing public read for now to ensure the dashboard works with the current anon key setup.
create policy "Allow public read for analytics"
on page_views
for select
to anon
using (true);
