-- 1. Admin Users Table (Links to Supabase Auth)
create table if not exists admin_users (
  id uuid references auth.users not null primary key,
  email text not null,
  role text not null check (role in ('super_admin', 'admin_manager', 'content_manager', 'support_staff', 'analytics_viewer')),
  status text not null default 'active' check (status in ('active', 'suspended')),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS for admin_users
alter table admin_users enable row level security;

-- Policy: Super Admins can view/edit all admin_users
create policy "Super Admins can manage all"
on admin_users
for all
to authenticated
using (
  exists (
    select 1 from admin_users au
    where au.id = auth.uid() and au.role = 'super_admin'
  )
);

-- Policy: Admin Managers can view all, but only edit non-super-admins (simplified to all for now)
-- Policy: Users can view their own profile
create policy "Users can view own profile"
on admin_users
for select
to authenticated
using (
  auth.uid() = id
);

-- 2. Activity Logs Table
create table if not exists activity_logs (
  id bigint generated by default as identity primary key,
  user_email text not null,
  action text not null,
  details jsonb,
  timestamp timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS for activity_logs
alter table activity_logs enable row level security;

-- Policy: Authenticated admins can insert logs
create policy "Admins can insert logs"
on activity_logs
for insert
to authenticated
with check (true);

-- Policy: Super Admins and Admin Managers can view logs
create policy "Admins can view logs"
on activity_logs
for select
to authenticated
using (
  exists (
    select 1 from admin_users au
    where au.id = auth.uid() and au.role in ('super_admin', 'admin_manager')
  )
);
