-- SITE CONTROL V1: Drafts and Versioning
-- Run this in the Supabase SQL Editor

-- 1. Site Drafts (Work in progress)
-- Stores the JSON layout of a page before it goes live.
CREATE TABLE IF NOT EXISTS site_drafts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    page_path TEXT NOT NULL UNIQUE, -- e.g., 'index.html'
    layout_json JSONB NOT NULL DEFAULT '[]'::JSONB,
    last_edited_by TEXT,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Site Versions (History)
-- Snapshot of published pages for rollback.
CREATE TABLE IF NOT EXISTS site_versions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    page_path TEXT NOT NULL,
    layout_json JSONB NOT NULL,
    version_label TEXT,
    published_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    published_by TEXT
);

-- 3. AI Assistant Logs (Optional but helpful for refinement)
CREATE TABLE IF NOT EXISTS ai_assistant_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    user_email TEXT,
    prompt TEXT,
    response TEXT,
    metadata JSONB
);

-- ENABLE REALTIME for Drafts
ALTER PUBLICATION supabase_realtime ADD TABLE site_drafts;
