-- Enable Row Level Security (RLS) is good practice, but for this simple setup we will start with public access or service role access.
-- Run this in the Supabase SQL Editor

-- 1. Heroes Table
create table heroes (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  age text,
  diagnosis text,
  story text,
  image text
);

-- 2. Events Table
create table events (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  date text,
  location text,
  description text
);

-- 3. About Page Content (Single row design)
create table about_page (
  id bigint generated by default as identity primary key,
  mission text,
  mission_extended text,
  gallery jsonb default '[]'::jsonb -- Storing gallery images as a JSON array
);

-- Insert initial row
insert into about_page (mission, mission_extended, gallery)
values (
  'Our mission is to bring hope, dignity, and support to children battling cancer by improving their quality of life and providing essential care. We do this by providing financial assistance for treatments, supplying essential care packages, and standing beside families throughout their journey.',
  'Founded on compassion and driven by community, Kids-Can Cancer Foundation exists to ensure no child fights cancer alone. We work tirelessly to fund medical treatments, improve living conditions for vulnerable families, and provide emotional strength through our network of care.',
  '[]'
);

-- 4. General Site Content (Optional, for other editable areas)
create table site_content (
  key text primary key,
  value text
);
create table page_views (
  id bigint generated by default as identity primary key,
  viewed_at timestamp with time zone default timezone('utc'::text, now()) not null,
  path text not null,
  user_agent text
);

