-- v2 SCHEMA UPDATE: Logs, Analytics, and Permissions

-- 1. ACTIVITY LOGS TABLE
create table if not exists activity_logs (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_email text not null,
  action text not null,
  details text
);

-- Enable RLS
alter table activity_logs enable row level security;

-- Policy: Authenticated admins can INSERT logs (anyone logged in)
create policy "Admins can insert logs"
on activity_logs for insert
to authenticated
with check ( true );

-- Policy: Only Super Admins and Managers can VIEW logs
-- (Depends on admin_users table existing)
create policy "Super Admins can view logs"
on activity_logs for select
to authenticated
using (
  exists (
    select 1 from admin_users au
    where au.email = auth.email()
    and au.role in ('super_admin', 'admin_manager')
  )
);


-- 2. PAGE VIEWS (Analytics) - Ensure it exists
create table if not exists page_views (
  id bigint generated by default as identity primary key,
  viewed_at timestamp with time zone default timezone('utc'::text, now()) not null,
  path text not null,
  user_agent text
);

-- Enable RLS
alter table page_views enable row level security;

-- Policy: Public can insert (tracking) - using anon key
create policy "Public can track views"
on page_views for insert
to anon, authenticated
with check ( true );

-- Policy: Admins can view analytics
create policy "Admins can view analytics"
on page_views for select
to authenticated
using (
  exists (
    select 1 from admin_users au
    where au.email = auth.email()
  )
);
